### ISSUE TITLE
Testbench Cases

### ISSUE THREAD

**Issue by markusc90** [DerekYu177/425G14#5]
All test cases to test for:

- [ ] Valid, Dirty, Read, Tag Equal

- [ ] Valid, Dirty, Read, Tag Unequal

- [ ] Valid, Dirty, Write, Tag Equal

- [ ] Valid, Dirty, Write, Tag Unequal

- [x] Valid, Not Dirty, Read, Tag Equal

- [ ] Valid, Not Dirty, Read, Tag Unequal

- [ ] Valid, Not Dirty, Write, Tag Equal

- [ ] Valid, Not Dirty, Write, Tag Unequal

- [ ] Invalid, Dirty, Read, Tag Equal (Not possible during operation)

- [ ] Invalid, Dirty, Read, Tag Unequal (Not possible during operation)

- [ ] Invalid, Dirty, Write, Tag Equal (Not possible during operation)

- [ ] Invalid, Dirty, Write, Tag Unequal (Not possible during operation)

- [x] Invalid, Not Dirty, Read, Tag Equal

- [ ] Invalid, Not Dirty, Read, Tag Unequal

- [ ] Invalid, Not Dirty, Write, Tag Equal

- [ ] Invalid, Not Dirty, Write, Tag Unequal

**Comment by DerekYu177** [comment]
👍

**Comment by DerekYu177** [comment]
LOL closing this
